version: '3.6'
services:
    vevor-ble-bridge:
        image: vevor-ble-bridge
        container_name: vevor_bridge
        network_mode: host
        restart: always
        cap_add:
            - NET_ADMIN
            - NET_RAW
        environment:
            BLE_MAC_ADDRESS: ${BLE_MAC_ADDRESS}
            BLE_PASSKEY: ${BLE_PASSKEY}
            DEVICE_NAME: ${DEVICE_NAME}
            DEVICE_MANUFACTURER: ${DEVICE_MANUFACTURER}
            DEVICE_MODEL: ${DEVICE_MODEL}
            MQTT_HOST: ${MQTT_HOST}
            MQTT_USERNAME: ${MQTT_USERNAME}
            MQTT_PASSWORD: ${MQTT_PASSWORD}
            MQTT_PREFIX: ${MQTT_PREFIX}
    vevor-restarter:
        image: docker
        container_name: vevor_bridge_restarter
        volumes: ["/var/run/docker.sock:/var/run/docker.sock"]
        command: ["/bin/sh", "-c", "while true; do sleep 3600; docker restart vevor_bridge; done"]
        restart: unless-stopped
